export { default as Home } from './Home'
export { default as Favorite } from './Favorite'
export { default as Categories } from './Categories'
export { default as List } from './List'
export { default as Details } from './Details'